---
- name: This is a hello-world example
  hosts: prueba, prueba2
  gather_facts: no
  tasks:

    - include: roles/init/tasks/main.yml

    - name: Simulate call collection
      block:

      - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
        debug:
          msg: "prueba"
        register: result
        ignore_errors: yes

      - pause: 
          seconds: 10

    - include: roles/finish/tasks/main.yml playbook_efficiencie_name=playbook3
